// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://noftpjabkurphbiiaqqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vZnRwamFia3VycGhiaWlhcXFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNjAxNjIsImV4cCI6MjA3MzgzNjE2Mn0.dOcyIPkBGRJk3Bnxu9-WsFsJouFIBwyhtHruwYqu6Xs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});